#!/usr/bin/env python3
"""
Generate and run KLayout DRC checks on a GDS file.
Usage: uv run drc.py <gds_file>
"""
import subprocess
import sys
import os
import tempfile

def generate_drc_script(gds_file: str, report_file: str) -> str:
    """Build a KLayout DRC script (Ruby) with common PIC checks."""
    return f"""
# KLayout DRC Script (auto-generated by drc.py)
source("{gds_file}")
report("DRC Report", "{report_file}")

# --- Layer definitions ---
wg = input(1, 0)   # waveguide layer

# --- DRC Rules ---

# Minimum width
wg.width(0.3).output("WG width", "Waveguide width < 0.3 um")

# Minimum spacing between waveguides
wg.space(0.2).output("WG space", "Waveguide spacing < 0.2 um")

# Minimum area (flag polygons smaller than 0.1 um^2)
wg.with_area(nil, 0.1).output("WG area", "Waveguide area < 0.1 um^2")
"""

def run_drc(gds_file: str):
    gds_file = os.path.abspath(gds_file)
    report_file = os.path.splitext(gds_file)[0] + "_drc.lyrdb"
    klayout_bin = "/Applications/klayout.app/Contents/MacOS/klayout"

    # Write DRC script to a temp file
    with tempfile.NamedTemporaryFile(suffix=".drc", mode="w", delete=False) as f:
        f.write(generate_drc_script(gds_file, report_file))
        drc_script = f.name

    print(f"Running DRC on: {gds_file}")
    print(f"Report will be saved to: {report_file}")

    try:
        subprocess.run(
            [klayout_bin, "-b", "-r", drc_script],
            check=True
        )
        print("DRC complete.")

        # Open GDS + report in KLayout
        subprocess.Popen([
            klayout_bin, "-e",
            gds_file,
            "-m", report_file,
        ])
        print("Opening results in KLayout...")
    finally:
        os.unlink(drc_script)

if __name__ == "__main__":
    gds = sys.argv[1] if len(sys.argv) > 1 else "example.gds"
    run_drc(gds)
