#!/usr/bin/env python3
"""
klayout_2p5DViews.py — Generate and install a KLayout 2.5D view macro for the PIC layer stack.

Writes mzi_view.lyd25 into the KLayout d25/PIXCEL_views folder so it appears under:
    Tools > 2.5D View > mzi_view

Then opens the GDS file in KLayout.

Usage:
    uv run klayout_2p5DViews.py [gds_file]
    uv run klayout_2p5DViews.py          # opens latest GDS from layout_gds/
"""
import os
import sys
import glob
import subprocess
from klayout_utils import load_env, get_klayout_bin, is_klayout_running

load_env()

BASE_DIR = os.path.dirname(os.path.abspath(__file__))

# KLayout user home: %HOMEPATH%\KLayout  (where d25/, macros/, drc/ live)
KLAYOUT_HOME = os.path.join(os.path.expanduser("~"), "KLayout")
D25_DIR      = os.path.join(KLAYOUT_HOME, "d25")
MACRO_FILE   = "pixcel_mzi_view.lyd25"

# PIC layer stack: (layer, datatype, name, zstart_um, zstop_um, 0xRRGGBB)
LAYER_STACK = [
    (2, 0, "Cladding (SiO2)",  -1.0,  2.0,   0xaaddff),
    (1, 0, "Waveguide (Si)",    0.0,   0.22,  0x778899),
    (3, 0, "Metal",             0.5,   1.0,   0xffd700),
]


def build_d25_script() -> str:
    """Return the Ruby DRC 2.5D script body using z() / zz() syntax."""
    lines = [
        "# PIC MZI 2.5D layer stack",
        "# Generated by klayout_2p5DViews.py",
        "# Layers extruded to their physical z-positions (values in um):",
        "",
    ]
    for layer, datatype, name, zstart, zstop, color in LAYER_STACK:
        lines.append(
            f'z(input({layer}, {datatype}), '
            f'zstart: {zstart}, zstop: {zstop}, '
            f'name: "{name}", color: 0x{color:06x})'
        )
    return "\n".join(lines)


def install_lyd25() -> str:
    """
    Write mzi_view.lyd25 as a KLayout macro XML file into the d25/ folder.
    The d25-dsl-xml interpreter is required for 2.5D scripts.
    Returns the installed file path.
    """
    script_body = build_d25_script()

    content = f"""<?xml version="1.0" encoding="utf-8"?>
<klayout-macro>
 <description/>
 <version/>
 <category>d25</category>
 <prolog/>
 <epilog/>
 <doc/>
 <autorun>false</autorun>
 <autorun-early>false</autorun-early>
 <priority>0</priority>
 <shortcut/>
 <show-in-menu>true</show-in-menu>
 <group-name>d25_scripts</group-name>
 <menu-path>tools_menu.d25.end</menu-path>
 <interpreter>dsl</interpreter>
 <dsl-interpreter-name>d25-dsl-xml</dsl-interpreter-name>
 <text>
{script_body}
 </text>
</klayout-macro>
"""
    lyd25_path = os.path.join(D25_DIR, MACRO_FILE)
    with open(lyd25_path, "w", encoding="utf-8") as f:
        f.write(content)
    return lyd25_path


def main():
    # Resolve GDS file
    if len(sys.argv) > 1:
        gds_file = os.path.abspath(sys.argv[1])
        if not os.path.exists(gds_file):
            print(f"Error: file not found: {gds_file}")
            sys.exit(1)
    else:
        gds_files = glob.glob(os.path.join(BASE_DIR, "layout_gds", "*.gds"))
        if not gds_files:
            print("No GDS files found in layout_gds/")
            sys.exit(1)
        gds_file = max(gds_files, key=os.path.getmtime)
        print(f"Latest GDS: {os.path.basename(gds_file)}")

    # Install 2.5D script
    lyd25_path = install_lyd25()
    print(f"2.5D script installed: {lyd25_path}")

    # Open KLayout
    klayout_bin = get_klayout_bin()
    running = is_klayout_running()
    if running:
        print("KLayout is already open — opening GDS in a new panel.")
        print("NOTE: Restart KLayout for the new macro to appear in the menu.")
    else:
        print("Launching KLayout (Editor).")

    subprocess.Popen([klayout_bin, "-e", gds_file])

    print()
    print(f"Opening: {gds_file}")
    print()
    print("To open the 2.5D view in KLayout:")
    print("  Tools > 2.5D View > mzi_view  (or load mzi_view.lyd25 from the script editor)")
    print()
    print("Layer stack:")
    for layer, dt, name, z0, z1, _ in LAYER_STACK:
        print(f"  {layer}/{dt}  {name:<20}  z = {z0:+.2f} .. {z1:.2f} um")


if __name__ == "__main__":
    main()
